# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170714_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courttype_master',
            name='CreateDate',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='SecondFunction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='myapp.Functions_Master'),
        ),
    ]
